### ISSUE TITLE
default_scope config is not being used

### ISSUE THREAD

**Issue by rschooley** [maxbeizer/ueberauth_heroku#3] opened 2018-03-18 20:34 UTC
I have the following configuration, but it does not change the requested token scope, it is always asking for identity.

```
config :ueberauth, Ueberauth,
  providers: [
    heroku: {Ueberauth.Strategy.Heroku, [default_scope: "global"]}
  ]
```

Appending the url args for `?scope=` works.

I also notice that using the url method above still has `scopes: [""]`.  Is that heroku just not spitting those values back, or is there a mapping issue in ueberauth_heroku / ueberauth?

**Comment by maxbeizer** [comment] 2019-01-14 21:36
hi @rschooley . I'm sorry I never saw a notification for this issue. I'd be happy to have a look asap

**Comment by maxbeizer** [comment] 2019-01-15 01:49
@rschooley sorry but I was unable to reproduce the issue you describe. I set up the example repo (which was a trip down memory lane). I ran it with the default config and it used the `identity` scope. I updated the config to `global` and restarted my server and I saw the below:

![screen shot 2019-01-14 at 7 43 18 pm](https://user-images.githubusercontent.com/2006658/51153238-06ec6600-1835-11e9-8eec-efc957c39a44.png)

Again sorry you had trouble with this. Did you remember to restart your server after changing config values?

I'm going to close this issue but feel free to reopen if you have a way I can reproduce.

**Closed as completed by maxbeizer** 2019-01-15 01:49 UTC
